# Generated by Django 5.1.15 on 2026-05-26 07:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import explorer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("function", "Function"),
                            ("class", "Class"),
                            ("method", "Method"),
                            ("module_construct", "Module Construct"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_line", models.IntegerField()),
                ("end_line", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "parent_block_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "explorer_codeblock",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("pt", "Portuguese"),
                            ("ja", "Japanese"),
                            ("ko", "Korean"),
                            ("zh", "Chinese (Simplified)"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("github_token_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "explorer_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BlockSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField()),
                (
                    "summary_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("permanently_failed", "Permanently Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("language", models.CharField(default="en", max_length=10)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="explorer.codeblock",
                    ),
                ),
            ],
            options={
                "db_table": "explorer_blocksummary",
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("github", "GitHub"), ("zip", "ZIP Upload")],
                        max_length=10,
                    ),
                ),
                (
                    "github_full_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("branch", models.CharField(blank=True, max_length=100, null=True)),
                ("commit_sha", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cloning", "Cloning"),
                            ("extracting", "Extracting"),
                            ("parsing", "Parsing"),
                            ("summarizing", "Summarizing"),
                            ("ready", "Ready"),
                            ("partially_summarized", "Partially Summarized"),
                            ("failed", "Failed"),
                        ],
                        default="cloning",
                        max_length=30,
                    ),
                ),
                ("file_count", models.IntegerField(default=0)),
                ("total_size_bytes", models.BigIntegerField(default=0)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "explorer_repository",
                "ordering": ["-ingested_at"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1000)),
                ("filename", models.CharField(max_length=255)),
                ("language", models.CharField(default="unknown", max_length=50)),
                ("content", models.TextField()),
                ("size_bytes", models.IntegerField()),
                ("is_summarizable", models.BooleanField(default=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="explorer.repository",
                    ),
                ),
            ],
            options={
                "db_table": "explorer_repositoryfile",
            },
        ),
        migrations.CreateModel(
            name="FileSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField()),
                (
                    "summary_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("permanently_failed", "Permanently Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("language", models.CharField(default="en", max_length=10)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="explorer.repositoryfile",
                    ),
                ),
            ],
            options={
                "db_table": "explorer_filesummary",
            },
        ),
        migrations.AddField(
            model_name="codeblock",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_blocks",
                to="explorer.repositoryfile",
            ),
        ),
        migrations.CreateModel(
            name="SharedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=explorer.models._generate_share_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_view",
                        to="explorer.repository",
                    ),
                ),
            ],
            options={
                "db_table": "explorer_sharedview",
            },
        ),
        migrations.CreateModel(
            name="SummarizationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("file", "File"), ("block", "Block")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("permanently_failed", "Permanently Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summarization_jobs",
                        to="explorer.codeblock",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summarization_jobs",
                        to="explorer.repositoryfile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summarization_jobs",
                        to="explorer.repository",
                    ),
                ),
            ],
            options={
                "db_table": "explorer_summarizationjob",
            },
        ),
        migrations.CreateModel(
            name="UsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repos_created", models.IntegerField(default=0)),
                ("files_processed", models.IntegerField(default=0)),
                ("summaries_generated", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "explorer_usagestats",
            },
        ),
        migrations.AddConstraint(
            model_name="repositoryfile",
            constraint=models.UniqueConstraint(
                fields=("repository", "path"), name="unique_repository_file_path"
            ),
        ),
        migrations.AddIndex(
            model_name="summarizationjob",
            index=models.Index(
                fields=["repository", "status"], name="sumjob_repo_status_idx"
            ),
        ),
    ]
