# Generated by Django 5.1.15 on 2026-06-03 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("explorer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=40,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Slug must start with a letter and contain only lowercase letters, numbers, and hyphens.",
                                regex="^[a-z][a-z0-9\\-]*$",
                            ),
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=39, null=True),
                ),
                ("skill_tags", models.JSONField(default=list)),
                ("follower_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "github_sync_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profiles_profile",
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to="profiles.profile",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_set",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profiles_follow",
            },
        ),
        migrations.CreateModel(
            name="ProjectEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="profiles.profile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_entries",
                        to="explorer.repository",
                    ),
                ),
            ],
            options={
                "db_table": "profiles_projectentry",
                "ordering": ["display_order", "-added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["slug"], name="profile_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["status"], name="profile_status_idx"),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "-created_at"], name="follow_follower_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["target", "-created_at"], name="follow_target_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("follower", "target"), name="unique_follow_relationship"
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                condition=models.Q(("follower", models.F("target")), _negated=True),
                name="no_self_follow",
            ),
        ),
        migrations.AddIndex(
            model_name="projectentry",
            index=models.Index(
                fields=["profile", "display_order"], name="project_profile_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectentry",
            constraint=models.UniqueConstraint(
                fields=("profile", "repository"), name="unique_profile_repository"
            ),
        ),
    ]
